[package]
name = "logviewer"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "*"
egui_extras = "*"
egui_tiles = "*"
rand = "*"
serde = "*"
serde_json = "*"
tokio = { version = "*", features = ["full"]}
eframe = "*"