/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 23
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_PIPE = 2,
  anon_sym_RBRACK = 3,
  aux_sym_operation_name_token1 = 4,
  anon_sym_AND = 5,
  anon_sym_OR = 6,
  anon_sym_NOT = 7,
  sym_query = 8,
  sym_operation = 9,
  sym_operation_name = 10,
  sym_operation_arguments = 11,
  sym_subquery = 12,
  sym_expression = 13,
  sym_term = 14,
  sym_logical_operator = 15,
  aux_sym_query_repeat1 = 16,
  aux_sym_expression_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_PIPE] = "|",
  [anon_sym_RBRACK] = "]",
  [aux_sym_operation_name_token1] = "operation_name_token1",
  [anon_sym_AND] = "AND",
  [anon_sym_OR] = "OR",
  [anon_sym_NOT] = "NOT",
  [sym_query] = "query",
  [sym_operation] = "operation",
  [sym_operation_name] = "operation_name",
  [sym_operation_arguments] = "operation_arguments",
  [sym_subquery] = "subquery",
  [sym_expression] = "expression",
  [sym_term] = "term",
  [sym_logical_operator] = "logical_operator",
  [aux_sym_query_repeat1] = "query_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_operation_name_token1] = aux_sym_operation_name_token1,
  [anon_sym_AND] = anon_sym_AND,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_NOT] = anon_sym_NOT,
  [sym_query] = sym_query,
  [sym_operation] = sym_operation,
  [sym_operation_name] = sym_operation_name,
  [sym_operation_arguments] = sym_operation_arguments,
  [sym_subquery] = sym_subquery,
  [sym_expression] = sym_expression,
  [sym_term] = sym_term,
  [sym_logical_operator] = sym_logical_operator,
  [aux_sym_query_repeat1] = aux_sym_query_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_operation_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_operation_name] = {
    .visible = true,
    .named = true,
  },
  [sym_operation_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_subquery] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_query_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == 'A') ADVANCE(2);
      if (lookahead == 'N') ADVANCE(3);
      if (lookahead == 'O') ADVANCE(4);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == '|') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'D') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'N') ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == 'O') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'R') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'T') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == '[') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_operation_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_AND);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_OR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_NOT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_query] = STATE(22),
    [anon_sym_LBRACK] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      aux_sym_operation_name_token1,
    STATE(3), 1,
      sym_term,
    STATE(8), 1,
      sym_subquery,
    STATE(9), 1,
      sym_query,
    STATE(18), 1,
      sym_operation_arguments,
    STATE(19), 1,
      sym_expression,
  [22] = 4,
    STATE(4), 1,
      aux_sym_expression_repeat1,
    STATE(10), 1,
      sym_logical_operator,
    ACTIONS(7), 2,
      anon_sym_PIPE,
      anon_sym_RBRACK,
    ACTIONS(9), 3,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
  [38] = 4,
    STATE(5), 1,
      aux_sym_expression_repeat1,
    STATE(10), 1,
      sym_logical_operator,
    ACTIONS(11), 2,
      anon_sym_PIPE,
      anon_sym_RBRACK,
    ACTIONS(9), 3,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
  [54] = 4,
    STATE(5), 1,
      aux_sym_expression_repeat1,
    STATE(10), 1,
      sym_logical_operator,
    ACTIONS(13), 2,
      anon_sym_PIPE,
      anon_sym_RBRACK,
    ACTIONS(15), 3,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
  [70] = 1,
    ACTIONS(18), 6,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
  [79] = 1,
    ACTIONS(20), 6,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
  [88] = 1,
    ACTIONS(22), 5,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
  [96] = 1,
    ACTIONS(24), 5,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
  [104] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 1,
      aux_sym_operation_name_token1,
    STATE(8), 1,
      sym_subquery,
    STATE(9), 1,
      sym_query,
    STATE(11), 1,
      sym_term,
  [120] = 1,
    ACTIONS(13), 5,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
  [128] = 3,
    ACTIONS(26), 1,
      anon_sym_PIPE,
    ACTIONS(28), 1,
      anon_sym_RBRACK,
    STATE(15), 1,
      aux_sym_query_repeat1,
  [138] = 3,
    ACTIONS(30), 1,
      aux_sym_operation_name_token1,
    STATE(2), 1,
      sym_operation_name,
    STATE(12), 1,
      sym_operation,
  [148] = 3,
    ACTIONS(30), 1,
      aux_sym_operation_name_token1,
    STATE(2), 1,
      sym_operation_name,
    STATE(21), 1,
      sym_operation,
  [158] = 3,
    ACTIONS(26), 1,
      anon_sym_PIPE,
    ACTIONS(32), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      aux_sym_query_repeat1,
  [168] = 3,
    ACTIONS(34), 1,
      anon_sym_PIPE,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      aux_sym_query_repeat1,
  [178] = 1,
    ACTIONS(39), 2,
      anon_sym_LBRACK,
      aux_sym_operation_name_token1,
  [183] = 1,
    ACTIONS(41), 2,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [188] = 1,
    ACTIONS(43), 2,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [193] = 1,
    ACTIONS(45), 2,
      anon_sym_LBRACK,
      aux_sym_operation_name_token1,
  [198] = 1,
    ACTIONS(37), 2,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [203] = 1,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 38,
  [SMALL_STATE(5)] = 54,
  [SMALL_STATE(6)] = 70,
  [SMALL_STATE(7)] = 79,
  [SMALL_STATE(8)] = 88,
  [SMALL_STATE(9)] = 96,
  [SMALL_STATE(10)] = 104,
  [SMALL_STATE(11)] = 120,
  [SMALL_STATE(12)] = 128,
  [SMALL_STATE(13)] = 138,
  [SMALL_STATE(14)] = 148,
  [SMALL_STATE(15)] = 158,
  [SMALL_STATE(16)] = 168,
  [SMALL_STATE(17)] = 178,
  [SMALL_STATE(18)] = 183,
  [SMALL_STATE(19)] = 188,
  [SMALL_STATE(20)] = 193,
  [SMALL_STATE(21)] = 198,
  [SMALL_STATE(22)] = 203,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 3, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 4, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subquery, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation_name, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation_arguments, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_operator, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_loguage(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "loguage",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
